#!/bin/bash
# Code generated by protoc-gen-liquibase. DO NOT EDIT.

# Command Arguments
CHANGEEXECLISTENERCLASS=${1}
CHANGEEXECLISTENERPROPERTIESFILE=${2}
CHANGELOGFILE=${3}
CONTEXTFILTER=${4}
DEFAULTCATALOGNAME=${5}
DEFAULTSCHEMANAME=${6}
DRIVER=${7}
DRIVERPROPERTIESFILE=${8}
LABELFILTER=${9}
PASSWORD=${10}
ROLLBACKONERROR=${11}
URL=${12}
USERNAME=${13}
# Global Options
ALWAYSDROPINSTEADOFREPLACE=${14}
ALWAYSOVERRIDESTOREDLOGICSCHEMA=${15}
AUTOREORG=${16}
CHANGELOGLOCKPOLLRATE=${17}
CHANGELOGLOCKWAITTIMEINMINUTES=${18}
CHANGELOGPARSEMODE=${19}
CLASSPATH=${20}
CONVERTDATATYPES=${21}
CUSTOMLOGDATAFILE=${22}
DATABASECHANGELOGLOCKTABLENAME=${23}
DATABASECHANGELOGTABLENAME=${24}
DATABASECLASS=${25}
DDLLOCKTIMEOUT=${26}
DEFAULTSFILE=${27}
DIFFCOLUMNORDER=${28}
DRIFTCHANGEDSEVERITY=${29}
DRIFTENABLED=${30}
DRIFTMISSINGSEVERITY=${31}
DRIFTREPORTENABLED=${32}
DRIFTREPORTFORMAT=${33}
DRIFTREPORTMODE=${34}
DRIFTREPORTNAME=${35}
DRIFTREPORTPATH=${36}
DRIFTUNEXPECTEDSEVERITY=${37}
DUPLICATEFILEMODE=${38}
ERRORONCIRCULARINCLUDEALL=${39}
FILEENCODING=${40}
FILTERLOGMESSAGES=${41}
FLOWVERBOSETOSTRING=${42}
GENERATECHANGESETCREATEDVALUES=${43}
GENERATEDCHANGESETIDSCONTAINSDESCRIPTION=${44}
HEADLESS=${45}
INCLUDECATALOGINSPECIFICATION=${46}
INCLUDESYSTEMCLASSPATH=${47}
LICENSEKEY=${48}
LIQUIBASECATALOGNAME=${49}
LIQUIBASESCHEMANAME=${50}
LIQUIBASETABLESPACENAME=${51}
LOGCHANNELS=${52}
LOGFILE=${53}
LOGFORMAT=${54}
LOGLEVEL=${55}
MIRRORCONSOLEMESSAGESTOLOG=${56}
MISSINGPROPERTYMODE=${57}
MONITORPERFORMANCE=${58}
NATIVEEXECUTOR=${59}
ONMISSINGINCLUDECHANGELOG=${60}
ONMISSINGSQLFILE=${61}
OUTPUTFILE=${62}
OUTPUTFILEENCODING=${63}
OUTPUTLINESEPARATOR=${64}
PRESERVESCHEMACASE=${65}
PROLICENSEKEY=${66}
PROMARKUNUSEDNOTDROP=${67}
PROSQLINLINE=${68}
PROSYNONYMSDROPPUBLIC=${69}
PROMPTFORNONLOCALDATABASE=${70}
PROPERTYPROVIDERCLASS=${71}
SEARCHPATH=${72}
SECUREPARSING=${73}
SHOULDRUN=${74}
SHOULDSNAPSHOTDATA=${75}
SHOWBANNER=${76}
SQLLOGLEVEL=${77}
SQLSHOWSQLWARNINGS=${78}
STRICT=${79}
SUPPORTPROPERTYESCAPING=${80}
USEPROCEDURESCHEMA=${81}
VALIDATEXMLCHANGELOGFILES=${82}

if [[ -z "$CHANGELOGFILE" ]]; then
	echo "changelogFile is required"
	exit 1
fi
if [[ -z "$URL" ]]; then
	echo "url is required"
	exit 1
fi

PARAMS=()

if [[ -n "$CHANGEEXECLISTENERCLASS" ]]; then
	PARAMS+=("--change-exec-listener-class=$CHANGEEXECLISTENERCLASS")
fi
if [[ -n "$CHANGEEXECLISTENERPROPERTIESFILE" ]]; then
	PARAMS+=("--change-exec-listener-properties-file=$CHANGEEXECLISTENERPROPERTIESFILE")
fi
if [[ -n "$CHANGELOGFILE" ]]; then
	PARAMS+=("--changelog-file=$CHANGELOGFILE")
fi
if [[ -n "$CONTEXTFILTER" ]]; then
	PARAMS+=("--context-filter=$CONTEXTFILTER")
fi
if [[ -n "$DEFAULTCATALOGNAME" ]]; then
	PARAMS+=("--default-catalog-name=$DEFAULTCATALOGNAME")
fi
if [[ -n "$DEFAULTSCHEMANAME" ]]; then
	PARAMS+=("--default-schema-name=$DEFAULTSCHEMANAME")
fi
if [[ -n "$DRIVER" ]]; then
	PARAMS+=("--driver=$DRIVER")
fi
if [[ -n "$DRIVERPROPERTIESFILE" ]]; then
	PARAMS+=("--driver-properties-file=$DRIVERPROPERTIESFILE")
fi
if [[ -n "$LABELFILTER" ]]; then
	PARAMS+=("--label-filter=$LABELFILTER")
fi
if [[ -n "$PASSWORD" ]]; then
	PARAMS+=("--password=$PASSWORD")
fi
if [[ -n "$ROLLBACKONERROR" ]]; then
	PARAMS+=("--rollback-on-error=$ROLLBACKONERROR")
fi
if [[ -n "$URL" ]]; then
	PARAMS+=("--url=$URL")
fi
if [[ -n "$USERNAME" ]]; then
	PARAMS+=("--username=$USERNAME")
fi

GLOBALS=()

if [[ -n "$ALWAYSDROPINSTEADOFREPLACE" ]]; then
	GLOBALS+=("--always-drop-instead-of-replace=$ALWAYSDROPINSTEADOFREPLACE")
fi
if [[ -n "$ALWAYSOVERRIDESTOREDLOGICSCHEMA" ]]; then
	GLOBALS+=("--always-override-stored-logic-schema=$ALWAYSOVERRIDESTOREDLOGICSCHEMA")
fi
if [[ -n "$AUTOREORG" ]]; then
	GLOBALS+=("--auto-reorg=$AUTOREORG")
fi
if [[ -n "$CHANGELOGLOCKPOLLRATE" ]]; then
	GLOBALS+=("--changelog-lock-poll-rate=$CHANGELOGLOCKPOLLRATE")
fi
if [[ -n "$CHANGELOGLOCKWAITTIMEINMINUTES" ]]; then
	GLOBALS+=("--changelog-lock-wait-time-in-minutes=$CHANGELOGLOCKWAITTIMEINMINUTES")
fi
if [[ -n "$CHANGELOGPARSEMODE" ]]; then
	GLOBALS+=("--changelog-parse-mode=$CHANGELOGPARSEMODE")
fi
if [[ -n "$CLASSPATH" ]]; then
	GLOBALS+=("--classpath=$CLASSPATH")
fi
if [[ -n "$CONVERTDATATYPES" ]]; then
	GLOBALS+=("--convert-data-types=$CONVERTDATATYPES")
fi
if [[ -n "$CUSTOMLOGDATAFILE" ]]; then
	GLOBALS+=("--custom-log-data-file=$CUSTOMLOGDATAFILE")
fi
if [[ -n "$DATABASECHANGELOGLOCKTABLENAME" ]]; then
	GLOBALS+=("--database-changelog-lock-table-name=$DATABASECHANGELOGLOCKTABLENAME")
fi
if [[ -n "$DATABASECHANGELOGTABLENAME" ]]; then
	GLOBALS+=("--database-changelog-table-name=$DATABASECHANGELOGTABLENAME")
fi
if [[ -n "$DATABASECLASS" ]]; then
	GLOBALS+=("--database-class=$DATABASECLASS")
fi
if [[ -n "$DDLLOCKTIMEOUT" ]]; then
	GLOBALS+=("--ddl-lock-timeout=$DDLLOCKTIMEOUT")
fi
if [[ -n "$DEFAULTSFILE" ]]; then
	GLOBALS+=("--defaults-file=$DEFAULTSFILE")
fi
if [[ -n "$DIFFCOLUMNORDER" ]]; then
	GLOBALS+=("--diff-column-order=$DIFFCOLUMNORDER")
fi
if [[ -n "$DRIFTCHANGEDSEVERITY" ]]; then
	GLOBALS+=("--drift-changed-severity=$DRIFTCHANGEDSEVERITY")
fi
if [[ -n "$DRIFTENABLED" ]]; then
	GLOBALS+=("--drift-enabled=$DRIFTENABLED")
fi
if [[ -n "$DRIFTMISSINGSEVERITY" ]]; then
	GLOBALS+=("--drift-missing-severity=$DRIFTMISSINGSEVERITY")
fi
if [[ -n "$DRIFTREPORTENABLED" ]]; then
	GLOBALS+=("--drift-report-enabled=$DRIFTREPORTENABLED")
fi
if [[ -n "$DRIFTREPORTFORMAT" ]]; then
	GLOBALS+=("--drift-report-format=$DRIFTREPORTFORMAT")
fi
if [[ -n "$DRIFTREPORTMODE" ]]; then
	GLOBALS+=("--drift-report-mode=$DRIFTREPORTMODE")
fi
if [[ -n "$DRIFTREPORTNAME" ]]; then
	GLOBALS+=("--drift-report-name=$DRIFTREPORTNAME")
fi
if [[ -n "$DRIFTREPORTPATH" ]]; then
	GLOBALS+=("--drift-report-path=$DRIFTREPORTPATH")
fi
if [[ -n "$DRIFTUNEXPECTEDSEVERITY" ]]; then
	GLOBALS+=("--drift-unexpected-severity=$DRIFTUNEXPECTEDSEVERITY")
fi
if [[ -n "$DUPLICATEFILEMODE" ]]; then
	GLOBALS+=("--duplicate-file-mode=$DUPLICATEFILEMODE")
fi
if [[ -n "$ERRORONCIRCULARINCLUDEALL" ]]; then
	GLOBALS+=("--error-on-circular-include-all=$ERRORONCIRCULARINCLUDEALL")
fi
if [[ -n "$FILEENCODING" ]]; then
	GLOBALS+=("--file-encoding=$FILEENCODING")
fi
if [[ -n "$FILTERLOGMESSAGES" ]]; then
	GLOBALS+=("--filter-log-messages=$FILTERLOGMESSAGES")
fi
if [[ -n "$FLOWVERBOSETOSTRING" ]]; then
	GLOBALS+=("--flow-verbose-to-string=$FLOWVERBOSETOSTRING")
fi
if [[ -n "$GENERATECHANGESETCREATEDVALUES" ]]; then
	GLOBALS+=("--generate-changeset-created-values=$GENERATECHANGESETCREATEDVALUES")
fi
if [[ -n "$GENERATEDCHANGESETIDSCONTAINSDESCRIPTION" ]]; then
	GLOBALS+=("--generated-changeset-ids-contains-description=$GENERATEDCHANGESETIDSCONTAINSDESCRIPTION")
fi
if [[ -n "$HEADLESS" ]]; then
	GLOBALS+=("--headless=$HEADLESS")
fi
if [[ -n "$INCLUDECATALOGINSPECIFICATION" ]]; then
	GLOBALS+=("--include-catalog-in-specification=$INCLUDECATALOGINSPECIFICATION")
fi
if [[ -n "$INCLUDESYSTEMCLASSPATH" ]]; then
	GLOBALS+=("--include-system-classpath=$INCLUDESYSTEMCLASSPATH")
fi
if [[ -n "$LICENSEKEY" ]]; then
	GLOBALS+=("--license-key=$LICENSEKEY")
fi
if [[ -n "$LIQUIBASECATALOGNAME" ]]; then
	GLOBALS+=("--liquibase-catalog-name=$LIQUIBASECATALOGNAME")
fi
if [[ -n "$LIQUIBASESCHEMANAME" ]]; then
	GLOBALS+=("--liquibase-schema-name=$LIQUIBASESCHEMANAME")
fi
if [[ -n "$LIQUIBASETABLESPACENAME" ]]; then
	GLOBALS+=("--liquibase-tablespace-name=$LIQUIBASETABLESPACENAME")
fi
if [[ -n "$LOGCHANNELS" ]]; then
	GLOBALS+=("--log-channels=$LOGCHANNELS")
fi
if [[ -n "$LOGFILE" ]]; then
	GLOBALS+=("--log-file=$LOGFILE")
fi
if [[ -n "$LOGFORMAT" ]]; then
	GLOBALS+=("--log-format=$LOGFORMAT")
fi
if [[ -n "$LOGLEVEL" ]]; then
	GLOBALS+=("--log-level=$LOGLEVEL")
fi
if [[ -n "$MIRRORCONSOLEMESSAGESTOLOG" ]]; then
	GLOBALS+=("--mirror-console-messages-to-log=$MIRRORCONSOLEMESSAGESTOLOG")
fi
if [[ -n "$MISSINGPROPERTYMODE" ]]; then
	GLOBALS+=("--missing-property-mode=$MISSINGPROPERTYMODE")
fi
if [[ -n "$MONITORPERFORMANCE" ]]; then
	GLOBALS+=("--monitor-performance=$MONITORPERFORMANCE")
fi
if [[ -n "$NATIVEEXECUTOR" ]]; then
	GLOBALS+=("--native-executor=$NATIVEEXECUTOR")
fi
if [[ -n "$ONMISSINGINCLUDECHANGELOG" ]]; then
	GLOBALS+=("--on-missing-include-changelog=$ONMISSINGINCLUDECHANGELOG")
fi
if [[ -n "$ONMISSINGSQLFILE" ]]; then
	GLOBALS+=("--on-missing-sql-file=$ONMISSINGSQLFILE")
fi
if [[ -n "$OUTPUTFILE" ]]; then
	GLOBALS+=("--output-file=$OUTPUTFILE")
fi
if [[ -n "$OUTPUTFILEENCODING" ]]; then
	GLOBALS+=("--output-file-encoding=$OUTPUTFILEENCODING")
fi
if [[ -n "$OUTPUTLINESEPARATOR" ]]; then
	GLOBALS+=("--output-line-separator=$OUTPUTLINESEPARATOR")
fi
if [[ -n "$PRESERVESCHEMACASE" ]]; then
	GLOBALS+=("--preserve-schema-case=$PRESERVESCHEMACASE")
fi
if [[ -n "$PROLICENSEKEY" ]]; then
	GLOBALS+=("--pro-license-key=$PROLICENSEKEY")
fi
if [[ -n "$PROMARKUNUSEDNOTDROP" ]]; then
	GLOBALS+=("--pro-mark-unused-not-drop=$PROMARKUNUSEDNOTDROP")
fi
if [[ -n "$PROSQLINLINE" ]]; then
	GLOBALS+=("--pro-sql-inline=$PROSQLINLINE")
fi
if [[ -n "$PROSYNONYMSDROPPUBLIC" ]]; then
	GLOBALS+=("--pro-synonyms-drop-public=$PROSYNONYMSDROPPUBLIC")
fi
if [[ -n "$PROMPTFORNONLOCALDATABASE" ]]; then
	GLOBALS+=("--prompt-for-non-local-database=$PROMPTFORNONLOCALDATABASE")
fi
if [[ -n "$PROPERTYPROVIDERCLASS" ]]; then
	GLOBALS+=("--property-provider-class=$PROPERTYPROVIDERCLASS")
fi
if [[ -n "$SEARCHPATH" ]]; then
	GLOBALS+=("--search-path=$SEARCHPATH")
fi
if [[ -n "$SECUREPARSING" ]]; then
	GLOBALS+=("--secure-parsing=$SECUREPARSING")
fi
if [[ -n "$SHOULDRUN" ]]; then
	GLOBALS+=("--should-run=$SHOULDRUN")
fi
if [[ -n "$SHOULDSNAPSHOTDATA" ]]; then
	GLOBALS+=("--should-snapshot-data=$SHOULDSNAPSHOTDATA")
fi
if [[ -n "$SHOWBANNER" ]]; then
	GLOBALS+=("--show-banner=$SHOWBANNER")
fi
if [[ -n "$SQLLOGLEVEL" ]]; then
	GLOBALS+=("--sql-log-level=$SQLLOGLEVEL")
fi
if [[ -n "$SQLSHOWSQLWARNINGS" ]]; then
	GLOBALS+=("--sql-show-sql-warnings=$SQLSHOWSQLWARNINGS")
fi
if [[ -n "$STRICT" ]]; then
	GLOBALS+=("--strict=$STRICT")
fi
if [[ -n "$SUPPORTPROPERTYESCAPING" ]]; then
	GLOBALS+=("--support-property-escaping=$SUPPORTPROPERTYESCAPING")
fi
if [[ -n "$USEPROCEDURESCHEMA" ]]; then
	GLOBALS+=("--use-procedure-schema=$USEPROCEDURESCHEMA")
fi
if [[ -n "$VALIDATEXMLCHANGELOGFILES" ]]; then
	GLOBALS+=("--validate-xml-changelog-files=$VALIDATEXMLCHANGELOGFILES")
fi

docker-entrypoint.sh "${GLOBALS[@]}" update-testing-rollback "${PARAMS[@]}"
